### ISSUE TITLE
Dev instructions fail

### ISSUE THREAD

**Issue by timlinux** [kartoza/qgis_geonode#102]
Using QGIS Master build

QGIS version | 3.17.0-Master | QGIS code revision | 4137287031
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.3 | Running against GDAL/OGR | 3.1.3
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.33.0 | Running against SQLite | 3.33.0
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.10.1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Pop!_OS 20.10 | This copy of QGIS writes debugging output.
Active python plugins | MetaSearch; processing; db_manager

Following the install notes at: https://kartoza.github.io/qgis_geonode/

![image](https://user-images.githubusercontent.com/178003/107937755-463d9180-6f7c-11eb-90c3-b5b6c769b0d9.png)

No plugins matching QGIS GeoNode search string are found:

![image](https://user-images.githubusercontent.com/178003/107937707-332ac180-6f7c-11eb-951a-49357b8c3018.png)

I guess your metadata assumes <= 3.16 for the QGIS Version?

**Comment by ricardogsilva** [comment]
@timlinux 

The plugin is currently flagged as `experimental` so you must be sure to enable the `Show also experimental plugins` checkbox in the plugin manager's Settings section - I can't see from the provided screenshots if that was already the case.

> I guess your metadata assumes <= 3.16 for the QGIS Version?

No, we are currently not checking for a QGIS maximum version (only that minumim is >= 3.10), so I think it should work with any new version

**Comment by ricardogsilva** [comment]
Opened an issue to check that Installation docs are current and work -> #104
