### ISSUE TITLE
Error loading plugin during API version setup

### ISSUE THREAD

**Issue by Samweli** [kartoza/qgis_geonode#105]
When plugin configuration are setup there is an error in assigning the Geonode API Version

![qgis_geonode_plugin_error](https://user-images.githubusercontent.com/2663775/108071390-bcbeba00-7076-11eb-92c8-e24051c0503f.png)

**Comment by ricardogsilva** [comment]
@Samweli 

I think you probably need to recreate your connections, as the recent work introduced some additional settings.

Try this out in the QGIS Python console:

```python
from qgis_geonode.conf import connections_manager
connections_manager.delete_all_connections()
connections_manager.clear_current_connection()
```

Then try again. Let me know if it works

**Comment by ricardogsilva** [comment]
@Samweli can I close this?

**Comment by Samweli** [comment]
> @Samweli can I close this?

yes @ricardogsilva
