### ISSUE TITLE
CSW API version's pagination does not work OK when setting page size < 10

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#127]

**Comment by Samweli** [comment]
@ricardogsilva this happens when page size is greater than 10 and it seems the CSW servers are not responding to the `maxrecords` property value.

**Comment by ricardogsilva** [comment]
@Samweli please check if this is still relevant as of the most recent code. If it is, there may be no way to fix it, if it depends on the CSW server

**Comment by ricardogsilva** [comment]
Check here for additional context:

https://github.com/geopython/pycsw/issues/294#issue-51565235

**Comment by Samweli** [comment]
@ricardogsilva I think this is not relevant anymore, tested the latest plugin code and couldn't reproduce it.
