### ISSUE TITLE
Loading the same layer twice errors when setting metadata and style

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#128]
When trying to load the same layer again after having closed and reopened the data source manager dialogue sometimes results in the following error messages:

```python
RuntimeError: wrapped C/C++ object of type QgsRasterLayer has been deleted 
Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/gui/search_result_widget.py", line 144, in prepare_layer
    self.populate_metadata(layer, geonode_resource)
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/gui/search_result_widget.py", line 158, in populate_metadata
    metadata = layer.metadata()
RuntimeError: wrapped C/C++ object of type QgsRasterLayer has been deleted
```

```python
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/gui/search_result_widget.py", line 230, in load_sld_layer
    loaded_sld = layer.readSld(sld_named_layer, error_message)
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
```

These messages appear multiple times. Despite the errors, QGIS is still able to load the layer, which seems wierd

**Comment by Samweli** [comment]
@ricardogsilva I have been trying to reproduce this on my side, but couldn't confirm it.

**Comment by ricardogsilva** [comment]
@Samweli 

Here is how to replicate it:

- Open QGIS data source manager and move to our GeoNode provider section
- Select a GeoNode instance and press `Search`
- Load one of the shown layers using WMS
- Close the data source manager
- Remove the layer from QGIS canvas
- Now reopen the data source manager and try to load the layer again, without refreshing the search

Here is a short video of it:


https://user-images.githubusercontent.com/732010/110318042-e8451c80-8004-11eb-9c4f-a10af041272e.mp4

**Comment by Samweli** [comment]
yes @ricardogsilva, I have confirmed it.

**Comment by Samweli** [comment]
@ricardogsilva I wonder if this is a QGIS bug or the plugin bug. I have not made any changes on the plugin code but right now I can't reproduce it again! see screenshot below

![can't_reproduce_anymore](https://user-images.githubusercontent.com/2663775/110476899-90d1aa00-80f3-11eb-8ecd-000f6c678648.gif)

**Comment by NyakudyaA** [comment]
Hi @Samweli I was testing this and it also occurred to me

![error-python](https://user-images.githubusercontent.com/2510900/110644637-fb4f1c80-81bd-11eb-8e94-2aea107d40f7.png)

**Comment by ricardogsilva** [comment]
I can't seem to reproduce this anymore. Maybe we fixed it accidentally during some of the latest refactorings. @NyakudyaA please report back if you can still reproduce it.

I'll close this for now, we will re-open if it makes sense
