### ISSUE TITLE
hook into QGIS data source manager dialog

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#13]
Add our initial search GUI, as implemented in #2 to the QGIS data source manager dialog, as researched in #4.

The main objective of this issue is to have our custom GUI show up when a user has the plugin loaded and opens up the QGIS data source manager. No need to actually connect our GUI's buttons to any actions at this point

**Comment by ricardogsilva** [comment]
@Samweli 

- Please provide an estimate for this task - add it as a label by using the labels that are already made. 
- After estimating, please move this to one of `ready` or `in progress` project columns

**Comment by Samweli** [comment]
ok @ricardogsilva
