### ISSUE TITLE
Update logic on resource type checkboxes with search buttons

### ISSUE THREAD

**Issue by Samweli** [kartoza/qgis_geonode#138]
Current state update logic between resource type checkboxes and search buttons can result into unwanted UI state.

Screenshot
![incorrect_next_previous_button](https://user-images.githubusercontent.com/2663775/110462688-0f255080-80e2-11eb-9fc8-ba73750f3f5a.gif)

**Comment by ricardogsilva** [comment]
Seems like we still have something to fix related to this, reopening...
