### ISSUE TITLE
Disable GeoNode search filtering widgets for now

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#27]
Currently our GeoNode search UI looks like this:

![disable_geonode_search_widgets](https://user-images.githubusercontent.com/732010/103780375-ccd18b80-502c-11eb-8c72-9862c3b88c9e.png)

since we are not making use of any search filtering functionality on our GeoNode API client class (I'm not even sure the GeoNode API supports these search filters yet), lets disable the widgets that allow filtering GeoNode layers (the ones in the section highlighted in red). It is very likely that filtering will only be implemented after our initial release.

**Comment by ricardogsilva** [comment]
Turns out there is support for GeoNode filters in the API already - check #29 

However, this issue still stands. We are not adding support for filtering yet, so lets disable these fields

**Comment by Samweli** [comment]
@ricardogsilva should we also disable the "Search Geonode" button?
