### ISSUE TITLE
Implement management of GeoNode connections

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#28]
Lets implement saving a GeoNode connection information.

- We need to hook up the GeoNode connection manager ui to the main plugin ui, as depicted in the picture below

![geonode_connection_manager](https://user-images.githubusercontent.com/732010/103781719-9eed4680-502e-11eb-8719-fcbac7c17122.png)

- Then we need to capture user input and save all connection information in the main `QSettings` object under our plugin's group. 

- We also need a way to show all available connections in the connection-choosing combobox

**Comment by Samweli** [comment]
> * Then we need to capture user input and save all connection information in the main `QSettings` object under our plugin's group.

@ricardogsilva shouldn't we use `QgsSettings` instead of `QSettings`?

**Comment by ricardogsilva** [comment]
> shouldn't we use QgsSettings instead of QSettings?

Sure, it definitely seems more appropriate. I wasn't aware of it actually :sweat_smile:
