### ISSUE TITLE
Implement search filters in the api client

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#29]
I've done some research on the current state of GeoNode's v2 API and could figure out how to filter requests (documentation on this is still lacking unfortunately). This means we can start adding support for filtering searches. 

Lets first focus on adding support and tests for these in the `apiclient.api_client.GeonodeClient` class. In a subsequent issue we will focus on hooking these to the GUI.

Implement support for filtering layers by the following attributes:

- [ ] **Free text** - Ideally we'd filter across multiple attributes for this like a resource's `title` and `abstract`. That does not seem to be supported by [dynamic-rest](https://github.com/AltSchool/dynamic-rest), which is the underlying API generation tech being used by geoNode, as shown in [this open issue](https://github.com/AltSchool/dynamic-rest/issues/253)
  
  We need to decide how to handle this (filter only by layer title? do multiple requests to filter in the layer title and the layer abstract and then merge the results? other solution?).

  Here is an example on how to filter on a layer's `title`:

  ```
  # find all layers that have `park` in their title
  https://master.demo.geonode.org/api/v2/layers?format=json&filter{title.icontains}=park
  ```

- [ ] **Keywords** - There does not seem to be an endpoint for knowing which keywords exist in GeoNode, at least not yet. As such, the best we can do for now is to use a line edit widget and let the user write down whatever words to be searched for. Example keywords search:

  ```
  # find all layers that have a keyword with a name that includes the string `drain`
  https://master.demo.geonode.org/api/v2/layers?format=json&filter{keywords.name.icontains}=drain
  ```

- [ ] **Topic category** - Topic category fields are taken from the [ISO 19115 topic categories list](https://apps.usgs.gov/thesaurus/thesaurus-full.php?thcode=15), so we just need to define an internal enum with their names (or maybe QGIS already has something like this, since it also uses these categories in its own metadata stuff) and use those to do a search like the following example:

  ```
  # filter by ISO Topic Category named `boundaries`
  https://master.demo.geonode.org/api/v2/layers?format=json&filter{category.identifier}=boundaries
  ```

- [ ] **Resource type** - Lets allow choosing between `vector layer`, `raster layer` and `map`. These will require performing alternative requests, as depicted in this example:

  ```
  # filter for raster layers
  https://master.demo.geonode.org/api/v2/layers?format=json&filter{storeType}=coverageStore

  # filter for vector layers
  https://master.demo.geonode.org/api/v2/layers?format=json&filter{storeType}=dataStore

  # filter for maps (uses a different endpoint)
  https://master.demo.geonode.org/api/v2/maps?format=json
  ```

**Comment by ricardogsilva** [comment]
@Samweli 

What is the status on this?

**Comment by Samweli** [comment]
> What is the status on this?

I''ll be opening a PR for this shortly.
