### ISSUE TITLE
Estimate effort needed to enable adding custom Python dialogues to QGIS data source manager

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#4]
QGIS datasource manager dialogue cannot currently be accessed via Python. For our concrete use-case it would be beneficial to be able to embed our GeoNode dialog into QGIS datasource manager.

Evaluate the effort needed to add this new functionality into QGIS core.

**Comment by Samweli** [comment]
@ricardogsilva can we close this? Based on the discussion we had, seems there is already an API in QGIS for this.
