### ISSUE TITLE
Implement loading a GeoNode layer into QGIS

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#56]
After #30 is done we shall be able to perform basic GeoNode layer searches.

Next up is being able to pick one GeoNode item from the ones returned in the search and load it into QGIS as a new layer.

The intended workflow is for a user to search for available GeoNode resources, then find the one(s) that are relevant and load them as QGIS layers by selecting one of the presented formats (i.e. WMS or WFS for vectors and WMS or WCS for rasters - maybe at a later stage we will implement direct data download, but not yet).

I understand that the current GeoNode REST API does not return URLs for accessing a layer's respective OGC services, so for now we will need to infer them from the GeoNode base URL and the layer's properties.

Do not worry about populating the QGIS layer's metadata tab with GeoNode-related metadata info yet. That shall be done at a later stage. Let's also leave retrieval and setting of the QGIS layer style to match GeoNode's for a later task too.

**Comment by ricardogsilva** [comment]
@Samweli what is the status of this? If the effort estimation is not correct, please update it.

**Comment by Samweli** [comment]
> @Samweli what is the status of this? If the effort estimation is not correct, please update it.

@ricardogsilva seeing this comment now, at the time of when you are asking this I had not started working on it, I moved this issue to the "on progress" list when I started working on it. I have opened a PR for it moments ago. thanks.
