### ISSUE TITLE
Clear current search results when a new search is requested by the user

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#71]
When the user presses either the `Search` or one of the pagination buttons we should clear the current search results, in anticipation of the new results which shall be arriving soon

**Comment by Samweli** [comment]
@ricardogsilva there is already a function that clear the search contents here `clear_search()` https://github.com/kartoza/qgis_geonode/blob/0fdab7959ae31fbaff30adb217f940e17d038514/src/qgis_geonode/gui/geonode_source_select_provider.py#L224 isn't this sufficient?

**Comment by ricardogsilva** [comment]
It probably is, but it must be hooked up to execute whenever a new search is initiated. It seems that part is missing
