### ISSUE TITLE
Add QGIS support for showing custom widgets to layer properties on raster layers

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#89]
According to qgis/QGIS#28060 there is currently no support in QGIS for showing a custom section on the layer properties dialogue of raster layers. This feature exists for vector layers though and we are planning on making it an important part of our UI.

Please add support for this in QGIS core.

Read the mentioned issue in order to get more details.

**Comment by Samweli** [comment]
See https://github.com/qgis/QGIS/pull/41557

**Comment by ricardogsilva** [comment]
Closing this, since @Samweli's work has been merged into QGIS core, nice work!
