### ISSUE TITLE
Please create basic developer docs

### ISSUE THREAD

**Issue by timlinux** [kartoza/qgis_geonode#92]
I would like to test the plugin as you work on it but I need basic information on how to get the plugin running on my system from a git clone. Please add to the readme.

**Comment by ricardogsilva** [comment]
We already have some docs for that here:

https://kartoza.github.io/qgis_geonode/development/

Perhaps you tried to access it straight from the README and it did not work -> which is a bug in the README :sweat_smile:

**Comment by timlinux** [comment]
> We already have some docs for that here:
> 
> https://kartoza.github.io/qgis_geonode/development/
> 
> Perhaps you tried to access it straight from the README and it did not work -> which is this bug in the README sweat_smile (#93)

Yes thanks that was what caught me out !
